// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aci.apic.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class Child {
    /**
     * @return Which class object is being created. (Make sure there is no colon in the classname)
     * 
     */
    private String class_name;
    /**
     * @return Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
     * 
     */
    private @Nullable Map<String,String> content;
    /**
     * @return Relative name of child object.
     * 
     */
    private String rn;

    private Child() {}
    /**
     * @return Which class object is being created. (Make sure there is no colon in the classname)
     * 
     */
    public String class_name() {
        return this.class_name;
    }
    /**
     * @return Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
     * 
     */
    public Map<String,String> content() {
        return this.content == null ? Map.of() : this.content;
    }
    /**
     * @return Relative name of child object.
     * 
     */
    public String rn() {
        return this.rn;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Child defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String class_name;
        private @Nullable Map<String,String> content;
        private String rn;
        public Builder() {}
        public Builder(Child defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.class_name = defaults.class_name;
    	      this.content = defaults.content;
    	      this.rn = defaults.rn;
        }

        @CustomType.Setter
        public Builder class_name(String class_name) {
            this.class_name = Objects.requireNonNull(class_name);
            return this;
        }
        @CustomType.Setter
        public Builder content(@Nullable Map<String,String> content) {
            this.content = content;
            return this;
        }
        @CustomType.Setter
        public Builder rn(String rn) {
            this.rn = Objects.requireNonNull(rn);
            return this;
        }
        public Child build() {
            final var o = new Child();
            o.class_name = class_name;
            o.content = content;
            o.rn = rn;
            return o;
        }
    }
}
