// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aci.apic;

import com.pulumi.aci.Utilities;
import com.pulumi.aci.apic.RestArgs;
import com.pulumi.aci.apic.outputs.Child;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages ACI Model Objects via REST API calls. This resource can only manage a single API object.
 * 
 */
@ResourceType(type="aci:apic:Rest")
public class Rest extends com.pulumi.resources.CustomResource {
    /**
     * List of child objects to be created. Each child object must have a unique relative name.
     * 
     */
    @Export(name="children", refs={List.class,Child.class}, tree="[0,1]")
    private Output</* @Nullable */ List<Child>> children;

    /**
     * @return List of child objects to be created. Each child object must have a unique relative name.
     * 
     */
    public Output<Optional<List<Child>>> children() {
        return Codegen.optional(this.children);
    }
    /**
     * Which class object is being created. (Make sure there is no colon in the classname)
     * 
     */
    @Export(name="class_name", refs={String.class}, tree="[0]")
    private Output<String> class_name;

    /**
     * @return Which class object is being created. (Make sure there is no colon in the classname)
     * 
     */
    public Output<String> class_name() {
        return this.class_name;
    }
    /**
     * Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
     * 
     */
    @Export(name="content", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> content;

    /**
     * @return Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
     * 
     */
    public Output<Optional<Map<String,String>>> content() {
        return Codegen.optional(this.content);
    }
    /**
     * Distinguished name of object being managed including its relative name, e.g. uni/tn-EXAMPLE_TENANT.
     * 
     */
    @Export(name="dn", refs={String.class}, tree="[0]")
    private Output<String> dn;

    /**
     * @return Distinguished name of object being managed including its relative name, e.g. uni/tn-EXAMPLE_TENANT.
     * 
     */
    public Output<String> dn() {
        return this.dn;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Rest(String name) {
        this(name, RestArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Rest(String name, RestArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Rest(String name, RestArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("aci:apic:Rest", name, args == null ? RestArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Rest(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("aci:apic:Rest", name, null, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Rest get(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Rest(name, id, options);
    }
}
