# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

insecure: Optional[bool]
"""
Allow insecure HTTPS client. This can also be set as the ACI_INSECURE environment variable. Defaults to true.
"""

logging: Optional[bool]
"""
Enable debug logging. This can also be set as the ACI_LOGGING environment variable. Defaults to false.
"""

password: str
"""
Password for the APIC Account. This can also be set as the ACI_PASSWORD environment variable.
"""

retries: Optional[int]
"""
Number of retries for REST API calls. This can also be set as the ACI_RETRIES environment variable. Defaults to 3.
"""

url: str
"""
URL of the Cisco APIC web interface. This can also be set as the ACI_URL environment variable.
"""

username: str
"""
Username for the APIC Account. This can also be set as the ACI_USERNAME environment variable.
"""

