// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aci;

import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("aci");
/**
 * Allow insecure HTTPS client. This can also be set as the ACI_INSECURE environment variable. Defaults to true.
 * 
 */
    public Optional<Boolean> insecure() {
        return Codegen.booleanProp("insecure").config(config).get();
    }
/**
 * Enable debug logging. This can also be set as the ACI_LOGGING environment variable. Defaults to false.
 * 
 */
    public Optional<Boolean> logging() {
        return Codegen.booleanProp("logging").config(config).get();
    }
/**
 * Password for the APIC Account. This can also be set as the ACI_PASSWORD environment variable.
 * 
 */
    public String password() {
        return Codegen.stringProp("password").config(config).env("ACI_PASSWORD").def("").require();
    }
/**
 * Number of retries for REST API calls. This can also be set as the ACI_RETRIES environment variable. Defaults to 3.
 * 
 */
    public Optional<Integer> retries() {
        return Codegen.integerProp("retries").config(config).get();
    }
/**
 * URL of the Cisco APIC web interface. This can also be set as the ACI_URL environment variable.
 * 
 */
    public String url() {
        return Codegen.stringProp("url").config(config).env("ACI_URL").def("").require();
    }
/**
 * Username for the APIC Account. This can also be set as the ACI_USERNAME environment variable.
 * 
 */
    public String username() {
        return Codegen.stringProp("username").config(config).env("ACI_USERNAME").def("").require();
    }
    public Optional<String> version() {
        return Codegen.stringProp("version").config(config).get();
    }
}
