// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aci;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * Allow insecure HTTPS client. This can also be set as the ACI_INSECURE environment variable. Defaults to true.
     * 
     */
    @Import(name="insecure", json=true)
    private @Nullable Output<Boolean> insecure;

    /**
     * @return Allow insecure HTTPS client. This can also be set as the ACI_INSECURE environment variable. Defaults to true.
     * 
     */
    public Optional<Output<Boolean>> insecure() {
        return Optional.ofNullable(this.insecure);
    }

    /**
     * Enable debug logging. This can also be set as the ACI_LOGGING environment variable. Defaults to false.
     * 
     */
    @Import(name="logging", json=true)
    private @Nullable Output<Boolean> logging;

    /**
     * @return Enable debug logging. This can also be set as the ACI_LOGGING environment variable. Defaults to false.
     * 
     */
    public Optional<Output<Boolean>> logging() {
        return Optional.ofNullable(this.logging);
    }

    /**
     * Password for the APIC Account. This can also be set as the ACI_PASSWORD environment variable.
     * 
     */
    @Import(name="password", required=true)
    private Output<String> password;

    /**
     * @return Password for the APIC Account. This can also be set as the ACI_PASSWORD environment variable.
     * 
     */
    public Output<String> password() {
        return this.password;
    }

    @Import(name="pluginDownloadURL")
    private @Nullable Output<String> pluginDownloadURL;

    public Optional<Output<String>> pluginDownloadURL() {
        return Optional.ofNullable(this.pluginDownloadURL);
    }

    /**
     * Number of retries for REST API calls. This can also be set as the ACI_RETRIES environment variable. Defaults to 3.
     * 
     */
    @Import(name="retries", json=true)
    private @Nullable Output<Integer> retries;

    /**
     * @return Number of retries for REST API calls. This can also be set as the ACI_RETRIES environment variable. Defaults to 3.
     * 
     */
    public Optional<Output<Integer>> retries() {
        return Optional.ofNullable(this.retries);
    }

    /**
     * URL of the Cisco APIC web interface. This can also be set as the ACI_URL environment variable.
     * 
     */
    @Import(name="url", required=true)
    private Output<String> url;

    /**
     * @return URL of the Cisco APIC web interface. This can also be set as the ACI_URL environment variable.
     * 
     */
    public Output<String> url() {
        return this.url;
    }

    /**
     * Username for the APIC Account. This can also be set as the ACI_USERNAME environment variable.
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return Username for the APIC Account. This can also be set as the ACI_USERNAME environment variable.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    @Import(name="version")
    private @Nullable Output<String> version;

    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.insecure = $.insecure;
        this.logging = $.logging;
        this.password = $.password;
        this.pluginDownloadURL = $.pluginDownloadURL;
        this.retries = $.retries;
        this.url = $.url;
        this.username = $.username;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param insecure Allow insecure HTTPS client. This can also be set as the ACI_INSECURE environment variable. Defaults to true.
         * 
         * @return builder
         * 
         */
        public Builder insecure(@Nullable Output<Boolean> insecure) {
            $.insecure = insecure;
            return this;
        }

        /**
         * @param insecure Allow insecure HTTPS client. This can also be set as the ACI_INSECURE environment variable. Defaults to true.
         * 
         * @return builder
         * 
         */
        public Builder insecure(Boolean insecure) {
            return insecure(Output.of(insecure));
        }

        /**
         * @param logging Enable debug logging. This can also be set as the ACI_LOGGING environment variable. Defaults to false.
         * 
         * @return builder
         * 
         */
        public Builder logging(@Nullable Output<Boolean> logging) {
            $.logging = logging;
            return this;
        }

        /**
         * @param logging Enable debug logging. This can also be set as the ACI_LOGGING environment variable. Defaults to false.
         * 
         * @return builder
         * 
         */
        public Builder logging(Boolean logging) {
            return logging(Output.of(logging));
        }

        /**
         * @param password Password for the APIC Account. This can also be set as the ACI_PASSWORD environment variable.
         * 
         * @return builder
         * 
         */
        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password Password for the APIC Account. This can also be set as the ACI_PASSWORD environment variable.
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        public Builder pluginDownloadURL(@Nullable Output<String> pluginDownloadURL) {
            $.pluginDownloadURL = pluginDownloadURL;
            return this;
        }

        public Builder pluginDownloadURL(String pluginDownloadURL) {
            return pluginDownloadURL(Output.of(pluginDownloadURL));
        }

        /**
         * @param retries Number of retries for REST API calls. This can also be set as the ACI_RETRIES environment variable. Defaults to 3.
         * 
         * @return builder
         * 
         */
        public Builder retries(@Nullable Output<Integer> retries) {
            $.retries = retries;
            return this;
        }

        /**
         * @param retries Number of retries for REST API calls. This can also be set as the ACI_RETRIES environment variable. Defaults to 3.
         * 
         * @return builder
         * 
         */
        public Builder retries(Integer retries) {
            return retries(Output.of(retries));
        }

        /**
         * @param url URL of the Cisco APIC web interface. This can also be set as the ACI_URL environment variable.
         * 
         * @return builder
         * 
         */
        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url URL of the Cisco APIC web interface. This can also be set as the ACI_URL environment variable.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        /**
         * @param username Username for the APIC Account. This can also be set as the ACI_USERNAME environment variable.
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username Username for the APIC Account. This can also be set as the ACI_USERNAME environment variable.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        public Builder version(String version) {
            return version(Output.of(version));
        }

        public ProviderArgs build() {
            $.password = Codegen.stringProp("password").secret().arg($.password).env("ACI_PASSWORD").def("").require();
            $.url = Codegen.stringProp("url").output().arg($.url).env("ACI_URL").def("").require();
            $.username = Codegen.stringProp("username").output().arg($.username).env("ACI_USERNAME").def("").require();
            return $;
        }
    }

}
