// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Manages ACI Model Objects via REST API calls. This resource can only manage a single API object.
 */
export class Rest extends pulumi.CustomResource {
    /**
     * Get an existing Rest resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Rest {
        return new Rest(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'aci:apic:Rest';

    /**
     * Returns true if the given object is an instance of Rest.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Rest {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Rest.__pulumiType;
    }

    /**
     * List of child objects to be created. Each child object must have a unique relative name.
     */
    public readonly children!: pulumi.Output<outputs.apic.Child[] | undefined>;
    /**
     * Which class object is being created. (Make sure there is no colon in the classname)
     */
    public readonly class_name!: pulumi.Output<string>;
    /**
     * Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
     */
    public readonly content!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Distinguished name of object being managed including its relative name, e.g. uni/tn-EXAMPLE_TENANT.
     */
    public readonly dn!: pulumi.Output<string>;

    /**
     * Create a Rest resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RestArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.class_name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'class_name'");
            }
            if ((!args || args.dn === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dn'");
            }
            resourceInputs["children"] = args ? args.children : undefined;
            resourceInputs["class_name"] = args ? args.class_name : undefined;
            resourceInputs["content"] = args ? args.content : undefined;
            resourceInputs["dn"] = args ? args.dn : undefined;
        } else {
            resourceInputs["children"] = undefined /*out*/;
            resourceInputs["class_name"] = undefined /*out*/;
            resourceInputs["content"] = undefined /*out*/;
            resourceInputs["dn"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Rest.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Rest resource.
 */
export interface RestArgs {
    /**
     * List of child objects to be created. Each child object must have a unique relative name.
     */
    children?: pulumi.Input<pulumi.Input<inputs.apic.ChildArgs>[]>;
    /**
     * Which class object is being created. (Make sure there is no colon in the classname)
     */
    class_name: pulumi.Input<string>;
    /**
     * Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
     */
    content?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Distinguished name of object being managed including its relative name, e.g. uni/tn-EXAMPLE_TENANT.
     */
    dn: pulumi.Input<string>;
}
