// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/netascode/pulumi-aci/sdk/go/aci/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Allow insecure HTTPS client. This can also be set as the ACI_INSECURE environment variable. Defaults to true.
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "aci:insecure")
}

// Enable debug logging. This can also be set as the ACI_LOGGING environment variable. Defaults to false.
func GetLogging(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "aci:logging")
}

// Password for the APIC Account. This can also be set as the ACI_PASSWORD environment variable.
func GetPassword(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "aci:password")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "ACI_PASSWORD"); d != nil {
		value = d.(string)
	}
	return value
}

// Number of retries for REST API calls. This can also be set as the ACI_RETRIES environment variable. Defaults to 3.
func GetRetries(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "aci:retries")
}

// URL of the Cisco APIC web interface. This can also be set as the ACI_URL environment variable.
func GetUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "aci:url")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "ACI_URL"); d != nil {
		value = d.(string)
	}
	return value
}

// Username for the APIC Account. This can also be set as the ACI_USERNAME environment variable.
func GetUsername(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "aci:username")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "ACI_USERNAME"); d != nil {
		value = d.(string)
	}
	return value
}
