// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aci.Apic.Outputs
{

    /// <summary>
    /// A child object to be created.
    /// </summary>
    [OutputType]
    public sealed class Child
    {
        /// <summary>
        /// Which class object is being created. (Make sure there is no colon in the classname)
        /// </summary>
        public readonly string Class_name;
        /// <summary>
        /// Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Content;
        /// <summary>
        /// Relative name of child object.
        /// </summary>
        public readonly string Rn;

        [OutputConstructor]
        private Child(
            string class_name,

            ImmutableDictionary<string, string>? content,

            string rn)
        {
            Class_name = class_name;
            Content = content;
            Rn = rn;
        }
    }
}
