// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aci.Apic
{
    /// <summary>
    /// Manages ACI Model Objects via REST API calls. This resource can only manage a single API object.
    /// </summary>
    [AciResourceType("aci:apic:Rest")]
    public partial class Rest : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of child objects to be created. Each child object must have a unique relative name.
        /// </summary>
        [Output("children")]
        public Output<ImmutableArray<Outputs.Child>> Children { get; private set; } = null!;

        /// <summary>
        /// Which class object is being created. (Make sure there is no colon in the classname)
        /// </summary>
        [Output("class_name")]
        public Output<string> Class_name { get; private set; } = null!;

        /// <summary>
        /// Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
        /// </summary>
        [Output("content")]
        public Output<ImmutableDictionary<string, string>?> Content { get; private set; } = null!;

        /// <summary>
        /// Distinguished name of object being managed including its relative name, e.g. uni/tn-EXAMPLE_TENANT.
        /// </summary>
        [Output("dn")]
        public Output<string> Dn { get; private set; } = null!;


        /// <summary>
        /// Create a Rest resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Rest(string name, RestArgs args, CustomResourceOptions? options = null)
            : base("aci:apic:Rest", name, args ?? new RestArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Rest(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("aci:apic:Rest", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/netascode",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Rest resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Rest Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Rest(name, id, options);
        }
    }

    public sealed class RestArgs : global::Pulumi.ResourceArgs
    {
        [Input("children")]
        private InputList<Inputs.ChildArgs>? _children;

        /// <summary>
        /// List of child objects to be created. Each child object must have a unique relative name.
        /// </summary>
        public InputList<Inputs.ChildArgs> Children
        {
            get => _children ?? (_children = new InputList<Inputs.ChildArgs>());
            set => _children = value;
        }

        /// <summary>
        /// Which class object is being created. (Make sure there is no colon in the classname)
        /// </summary>
        [Input("class_name", required: true)]
        public Input<string> Class_name { get; set; } = null!;

        [Input("content")]
        private InputMap<string>? _content;

        /// <summary>
        /// Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
        /// </summary>
        public InputMap<string> Content
        {
            get => _content ?? (_content = new InputMap<string>());
            set => _content = value;
        }

        /// <summary>
        /// Distinguished name of object being managed including its relative name, e.g. uni/tn-EXAMPLE_TENANT.
        /// </summary>
        [Input("dn", required: true)]
        public Input<string> Dn { get; set; } = null!;

        public RestArgs()
        {
        }
        public static new RestArgs Empty => new RestArgs();
    }
}
