// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aci.Apic.Inputs
{

    public sealed class ChildArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Which class object is being created. (Make sure there is no colon in the classname)
        /// </summary>
        [Input("class_name", required: true)]
        public Input<string> Class_name { get; set; } = null!;

        [Input("content")]
        private InputMap<string>? _content;

        /// <summary>
        /// Map of key-value pairs those needed to be passed to the Model object as parameters. Make sure the key name matches the name with the object parameter in ACI.
        /// </summary>
        public InputMap<string> Content
        {
            get => _content ?? (_content = new InputMap<string>());
            set => _content = value;
        }

        /// <summary>
        /// Relative name of child object.
        /// </summary>
        [Input("rn", required: true)]
        public Input<string> Rn { get; set; } = null!;

        public ChildArgs()
        {
        }
        public static new ChildArgs Empty => new ChildArgs();
    }
}
